import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBanner from "@/components/home/TopBanner";
import Header from "@/components/common/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      {/*<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>*/}
      <body>
        <TopBanner />
        <Header />
        {children}
      </body>
    </html>
  );
}
